[plugin]
repository = "https://github.com/chirpxiv/SelfCare.git"
commit = "f0c9e12b5d2f74d7baa9dc76748d9f9ca1784cc1"
owners = ["chirpxiv"]
project_path = "SelfCare"
changelog = """
- Updated for Dalamud API 9
- Added a new icon (thanks @oikvw)!
"""